# Generated by Django 3.1 on 2020-08-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='Product',
            name='summary',
            field=models.TextField(default='this is default'),
        ),
    ]
