# Generated by Django 3.1 on 2020-08-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200820_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='Product',
            name='featured',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
