# Generated by Django 3.1 on 2020-08-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Product',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
